import '@styles/global.css'
import Spinner from "@components/spinner"
export const metadata  = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout = ({children}) => {
  return (
      <html lang="en">
          <body >
          {/* <div className="main">
            <div className="gradient"/>
          </div> */}
            <header className="bg-neutral-800 p-5">
            <h1 className="mt-10 mb-8 text-center capatalize text-4xl font-work italic font-bold text-white">Styles Store</h1>
            </header>
          <hr  className="w-full "/>
          <main>{children}</main>
          <Spinner/>
          </body>
          

      </html>
  )
}

export default RootLayout;